lima-dove/311-Capstone

.travis.yml
package-lock.json

added secure API key for travis CI

feat: add travis for CI

---

.travis.yml
client/components/navbar.js
package-lock.json
package.json
public/index.html

fix: changed name in package.json and front end, add travis slack

---

client/components/Firebase.js
client/components/index.js
client/firebase.js
client/routes.js
package-lock.json
package.json
public/index.html

feat: connect firebase

---

client/components/ExampleComplaints.js
client/routes.js
package-lock.json
package.json

graph 311 data, use it to generate info for bar chart and line graph (year of complaint, frequency, type)

feat: grabbing API data, computing bar chart / line graph info w/ data

---

client/components/HomePage.js
client/components/navbar.js
package-lock.json
public/style.css

style: change navbar and map format

---

client/components/HomePage.js
package-lock.json

feat: map over initial query and place markers on map

---

client/components/AuthForm.js

FEAT: format 'sign in' component with material ui

---

client/components/HomePage.js

feat: add map popup on marker click with sample graph and info

---

client/components/GraphTest.js
client/components/PieChart.js
package-lock.json
package.json
public/style.css

feat:add pie-chart on graph page

---

client/components/BarGraphTest.js
client/components/GraphTest.js
client/components/HomePage.js
client/components/LineGraph.js
public/style.css

Bar graph: bar color based on frequency, bar spacing centered on tick (bandwidth), # ticks = # complaints

---

tests/seed.spec.js

fix: seed test handling promices

---

package.json
script/seedCenter.js
server/db/models/neighborhood.js

Hood center

---

client/components/HomePage.js

Marker render logic

---

client/components/HomePage.js
server/api/map.js

Refactor routes

---

client/components/HomePage.js

add fly to functionality on search

---

client/components/BarGraphTest.js
client/components/HomePage.js
client/components/InfoPage.js

refactor: delete console logs and commented code

---

server/db/models/index.js
server/db/models/user_complaint.js

feat: add user_complaint table

---

client/components/Sidebar.js
public/index.html
public/style.css

feat: add address and neighborhood zoom view icons to sidebar

---

server/api/index.js
server/api/user-complaint.js
server/db/models/user.js
server/db/models/user_complaint.js
tests/user.spec.js
tests/users.spec.js

feat: add user complaint routes (get, post, put)

---

server/api/map.js

feat:search for null address works by coordinates range

---

client/components/BarGraphTest.js
client/components/GraphTabs.js
client/components/HomePage.js
client/components/InfoPage.js
client/components/UserComplaintForm.js
client/components/UserResolutionForm.js
client/components/navbar.js
public/style.css

Complaint bug fix

---

client/components/NeighborhoodInfoPage.js
public/style.css

style: total complaints style

---

client/components/navbar.js

fix: put home back on the map

---

client/components/HomePage.js
client/components/Sidebar.js

fix: made zoom level change closer

---

client/components/navbar.js

feat: make home button a routerLink and redirect to home

---

client/components/HomePage.js
client/components/Sidebar.js

feat: sidebar scrolls (added overflow), upon mouse enter map scroll turns off

Sidebar scroll click

---

client/components/InfoPage.js
client/components/UserComplaintForm.js
package-lock.json
package.json
server/api/email.js
server/api/index.js
server/api/map.js
server/api/user-complaint.js

Email notification
